twitter {
  api-url = "https://api.twitter.com/2/tweets/search/recent"
  timeout = 30s
}

kafka { # todo
  bootstrap-servers = "localhost:9092"
  topic = "raw-tweets"
}

collector {
  default {
    interval = 10 seconds
    max-results = 50
    enabled = true
    priority = 3
  }

  tags = [
    {
      name = "scala"
      interval = 16 minutes
      max-results = 10
      priority = 1
    },
    {
      name = "akka",
      interval = 15 seconds,
      enabled = false
    },
    {
      name = "spark",
      max-results = 30
      enabled = false
    }
  ]
}